version: "3.9"

services:
  chat-app-db:
    container_name: "chat-app-db"
    image: "postgres:17.0-bullseye"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      # external:internal
      - "5445:5432"
    volumes:
      - "chatpp-app-db-postgres-volume:/var/lib/postgresql/data"

volumes:
  chatpp-app-db-postgres-volume: